### ISSUE TITLE
Conditional statements

### ISSUE THREAD

**Issue by jquorning** [AdaCore/ada-spark-rfcs#59]
## Proposal
Statements are changed to allow conditional execution thereof based on the value of a boolean expression.
The `when` keyword should be used to indicate a conditional statement.

## Examples
```ada
Stop (Car, Emergency) when PB_EMCY;
--  Emergency stop Car when the pushbutton PB_EMCY is pressed.

Compile when Change or Force_Compile;

LED_05 := Set   when PB_Start;
LED_05 := Clear when PB_Stop;
--  SR Flip-Flop.
```

## Rationale
It would be nice to be able to execute a statement depending on when a boolean expression evaluates to `True`.
In many cases the program text would be shorter and arguably easier to read.

## Implementation
It should be easy to implement in the compiler.

## Alternative
```ada
when PB_Start then LED_05 := True;
when PB_Stop  then LED_05 := False;
--  SR Flip-Flop with focus on inputs.
--  The SR-FF in exmples has focus on output.
```

**Comment by raph-amiard** [comment]
Hi @jquorning.

While I appreciate that you wrote a code sample that allows one to infer what feature you would like, I must say this is still not enough for what we expect of an issue here:

- At least give a small rationale of why you think this would be worthwile, what problems it would solve, etc.
- Also give some thought to formatting, and try to make your code valid Ada except for the parts that concern the features you are describing (I edited your text to make the above a code block, but that's all I did, and I did not remove the invalid operators).

In the future, we would appreciate if you give some thought to your proposal by writing something with a minimum of polish before posting it here :slightly_smiling_face: Thanks in advance.

**Comment by jquorning** [comment]
@raph-amiard ,
Thank You for your feedback. I home my latest changes bring more clarity to the proposed issue :-)

**Comment by senier** [comment]
> In the future, we would appreciate if you give some thought to your proposal by writing something with a minimum of polish before posting it here slightly_smiling_face Thanks in advance.

@raph-amiard Maybe you should consider using [issue templates](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) to suggest a structure for new issues?

**Comment by raph-amiard** [comment]
@senier that's a great point, especially considering we have a template for RFCs, but not for issues! Thanks for the suggestion, we'll consider this.

**Comment by raph-amiard** [comment]
@senier You'll be glad to know that we have issue templates now :wink:
