### ISSUE TITLE
[feature] Allow handling of Storage_Error in Spark

### ISSUE THREAD

**Issue by mhatzl** [AdaCore/ada-spark-rfcs#78]
### Summary

Provide a possibility to handle `Storage_Error` in Spark_Mode. 

### Motivation

Currently, exception handling is not allowed in Spark. Since the abscence of all run-time errors except `Storage_Error` can be proven, I don't see a way to write a full program in Spark_Mode.  
If one writes most code in Spark_Mode, except at program entry to handle a `Storage_Error`, one might lose the possibility to safely recover from the exception.

See: [How to check for Storage_Error in Spark_Ada](https://stackoverflow.com/questions/67806008/how-to-check-for-storage-error-in-spark-ada/67809949#67809949) for further motivation

### Caveats and alternatives

Adding full exception handling support is probably beyond any achievable scope, but maybe an alternative can be found since it is only one specific exception.  
As an alternative, some kind of size check could be used to compare the available stack/heap size with the size that will be allocated, but this might result in a lot of if-checks.

**Comment by yannickmoy** [comment]
`Storage_Error` is related to the hardware/OS configuration, and so cannot be analyzed by a tool like GNATprove which takes the software only as input. It's similar to other things at the boundary of software, like the addresses you use for certain memory-mapped variables. For storage errors, it's rarely the case that you can recover at any point in the code, can you tell more about your use case?

**Comment by glacambre** [comment]
@yannickmoy I don't know how that relates to @mhatzl use case, but being able to recover from allocation failures is very important in the Linux kernel and is in fact of the major arguments against using Rust in that setting (see https://lkml.org/lkml/2021/4/14/1099 ).

**Comment by yannickmoy** [comment]
@glacambre In that case, the solution outlined in [How to check for Storage_Error in Spark_Ada](https://stackoverflow.com/questions/67806008/how-to-check-for-storage-error-in-spark-ada/) seems to be adequate, with minimal use of SPARK_Mode=>Off just inside the allocation function allowed to fail. Note that you could also return a possibly null pointer instead of a discriminated record if you prefer, which would mimic the C interface for allocation. And GNATprove will check that you never dereference a null pointer in the caller.

**Comment by mhatzl** [comment]
Thanks for your fast responses.
As for the use case, I was thinking about programming an unbound (generic) AVL-tree in Spark with gold/platinum level as my bachelor thesis, since I have not yet found any unbound implementation online (not yet sure how "doable" this is). Since I want the tree to be unbounded, I have to use dynamic allocation.  
And with dynamic allocation, I was looking for a way on how to handle the case when there is no memory left on the heap, which got me to the `Storage_Error` exception. With the example given at [How to check for Storage_Error in Spark_Ada](https://stackoverflow.com/questions/67806008/how-to-check-for-storage-error-in-spark-ada/67809949?noredirect=1#comment119862466_67809949), there is a good way on solving this.  
However, I thought it would be nice to have a way to write everything in Spark_Mode. If I am correct, with Spark and GNATstack, a stackoverflow can not happen, which would leave only the `new` keyword for a place where a `Storage_Error`could occur.

Would it be possible to have specific code blocks, where only allocations are made and in this code block, handling `Storage_Error` would be allowed with Spark_Mode?

As my use case is purely personal, it has absolutely no priority. I just wanted to better understand Ada and Spark and hear other opinions.

**Comment by Fabien-Chouteau** [comment]
> Would it be possible to have specific code blocks, where only allocations are made and in this code block,

I was going to suggest that, you can put the allocation/deallocation in a specific part of you code that will handle `Storage_Error`.

> handling `Storage_Error` would be allowed with Spark_Mode?

I don't think so, but mixing SPARK and Ada code is actually a good strategy for this kind of situations.
You can probably have a `Spark_Mode => On` specification for the sub-program that handles allocation and then just the implementation (body) in `Spark_Mode => Off`. This implementation will have to be verified through unit testing for instance, but it should be a very small piece of code so it is not too much of an issue.

Something like:
```ada
package SPARK_Alloc
  with SPARK_Mode
is
   type Int_Acc is access Integer;
   function Alloc return Int_Acc;
   procedure Free (Ptr : in out Int_Acc);
end SPARK_Alloc;
```
```ada
with Ada.Unchecked_Deallocation;
package body SPARK_Alloc
  with SPARK_Mode => Off
is
   procedure Dealloc is new Ada.Unchecked_Deallocation (Integer, Int_Acc);

   function Alloc return Int_Acc is
   begin
      declare
         Ptr : Int_Acc := new Integer;
      begin
         return Ptr;
      exception
         when Storage_Error =>
            return null;
      end;
   end Alloc;

   procedure Free (Ptr : in out Int_Acc) is
   begin
      Dealloc (Ptr);
   end Free;
end SPARK_Alloc;
```

Then when you use this allocator in your code GNATprove will make sure that you don't de-reference a null access.
For instance, this:
```ada
with SPARK_Alloc; use SPARK_Alloc;
procedure Main
  with SPARK_Mode
is
   Ptr : SPARK_Alloc.Int_Acc := SPARK_Alloc.Alloc;
begin
   Ptr.all := 42;
   SPARK_Alloc.Free (Ptr);
end Main;
```
will produce a GNATprove message: `main.adb:7:08: medium: pointer dereference check might fail[#0]`
So SPARK will make sure that you handle properly the case where the allocation fails.

**Comment by clairedross** [comment]
> with Ada.Unchecked_Deallocation;package body SPARK_Alloc
>   with SPARK_Mode => Offis
>    procedure Dealloc is new Ada.Unchecked_Deallocation (Integer, Int_Acc);
>
>    function Alloc return Int_Acc is
>    begin
>       declare
>          Ptr : Int_Acc := new Integer;
>       begin
>          return Ptr;
>       exception
>          when Storage_Error =>
>             return null;
>       end;
>    end Alloc;
>
>    procedure Free (Ptr : in out Int_Acc) is
>    begin
>       Dealloc (Ptr);
>    end Free;end SPARK_Alloc;
>
> Note that you can put the SPARK_Mode => Off annotation on the body of
Alloc instead as deallocation is supported in SPARK.

-- 
Claire Dross
Senior Software Engineer, AdaCore

**Comment by mhatzl** [comment]
Thanks again for the response.
I will try to use this approach in my implementations.

Since handling of `Storage_Error` inside Spark will not be implemented, the issue can be closed from my point of view.

**Comment by yannickmoy** [comment]
Thanks @mhatzl for the feedback, I'll close that Issue then.
